name: Build static pages and upload to Vercel

on:
  push:
    branches: ['**']
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  vercel:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup install stable
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Install Dioxus
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall dioxus-cli
      
      - name: Verify installations
        run: |
          rustc --version
          cargo --version
          dx --version

      - name: Install dependencies and build web pages
        working-directory: ./profile/
        run: |
          npm install
          dx build --release --platform web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./target/dx/profile/release/web/public/
